/* Share page: a QR code that opens the interview, plus a copyable link.

   The QR image is generated by the backend (/api/qr), which only encodes
   addresses on an allowed origin. The link points at demo.html next to this
   page, so it works on GitHub Pages sub-paths as well as a root domain. */

function interviewUrl() {
  return new URL('demo.html', location.href).href;
}

async function showQr() {
  const url = interviewUrl();
  document.getElementById('shareUrl').textContent = url;

  const frame = document.getElementById('qrFrame');
  const error = document.getElementById('qrError');
  const img = document.getElementById('qrImage');

  try {
    // Fetch as a blob so a failure shows a message instead of a broken image icon.
    const res = await fetch(`${CC.apiBase}/api/qr?url=${encodeURIComponent(url)}`);
    if (!res.ok) throw new Error('bad status');
    img.src = URL.createObjectURL(await res.blob());
    frame.hidden = false;
    error.hidden = true;
  } catch (e) {
    frame.hidden = true;
    error.textContent = CC.t('share.noBackend');
    error.hidden = false;
  }
}

document.addEventListener('DOMContentLoaded', () => {
  CC.applyI18n();
  CC.mountLangToggle();
  showQr();

  const copyBtn = document.getElementById('copyBtn');
  copyBtn.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(interviewUrl());
      copyBtn.textContent = CC.t('share.copied');
      setTimeout(() => { copyBtn.textContent = CC.t('share.copy'); }, 1500);
    } catch (e) { /* clipboard blocked: the address is still on screen */ }
  });

  document.addEventListener('cc:langchange', () => {
    if (!document.getElementById('qrError').hidden) {
      document.getElementById('qrError').textContent = CC.t('share.noBackend');
    }
  });
});
